# 将来如果要多语言，把本文件重命名为 languages.toml 即可启用

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Capriccio"
weight = 1

# 如果以后要加英文，可以再加一个：
#[en]
#languageName = "English"
#languagedirection = "ltr"
#title = "Capriccio"
#weight = 2
