baseurl = "https://QC-Faith.github.io/Capriccio/"
languageCode = "zh-cn"
title = "Capriccio"

# 默认语言与中文支持
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

enableRobotsTXT = true


[pagination]
pagerSize = 10

# ✅ PaperMod 搜索需要 home 输出 JSON
[outputs]
home = ["HTML", "RSS", "JSON"]
