baseURL = "https://QC-Faith.github.io/Capriccio/"
title = "Capriccio"

languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

paginate = 10          # 每页文章数量
enableRobotsTXT = true # 生成 robots.txt

# 这里写 PaperMod 主题名称（虽然我们用的是 Modules，但写上也没坏处）
theme = "PaperMod"
