# Configure main menu and social menu

# 想在顶部导航加“首页 / 归档 / 关于”等，可以在这里启用 main 菜单
# 示例：
# [[main]]
# identifier = "home"
# name = "首页"
# url = "/"
# [main.params]
# icon = "home"
# newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/QC-Faith"
[social.params]
icon = "brand-github"

# 没有 Twitter 或暂时不用就先注释掉
# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"
# [social.params]
# icon = "brand-twitter"
