# 顶部导航菜单

[[main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 10

[[main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 20

[[main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 40
